
site_name: Coms Term

nav:
# rest of the navigation...
# defer to gen-files + literate-nav
- Home: index.md
- Code Reference: reference/  
# rest of the navigation...

theme:
  name: material

  features:
    - navigation.indexes
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
- search:
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        python:
          options:
            show_submodules: true
            allow_inspection: true
